customer/urls.py
from django.urls import path, reverse
from . import views

urlpatterns = [
    path('', views.CustomerListView.as_view(), name='index'),
    path('<int:pk>/', views.CustomerDetailView.as_view(), name="detail"),
    path('edit/<int:pk>/', views.CustomerUpdateView.as_view(), name='edit'),
    path('add/', views.CustomerCreateView.as_view(), name='add'),
    path('delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='delete'),
]

dag_backend/customer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CustomerList.as_view()),
    path('<int:pk>/', views.CustomerDetail.as_view()),
    path('inquiry/', views.InquiryList.as_view()),
    path('inquiry/<int:pk>/', views.InquiryDetail.as_view()),
]

dag_backend/dag_backend/urls.py
from django.contrib import admin
from django.urls import path, include
# from customer.admin import my_site

urlpatterns = [
    path('customer/',include('customer.urls')),
     path('inspection/', include('inspection.urls')),
    path('admin/', admin.site.urls),
    # path('admin/', my_site.urls),
]

dag_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# from customer.admin import my_site

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('customer/',include(('customer.urls','customer'), namespace='customer')),
    path('inspection/', include(('inspection.urls','inspection'), namespace='inspection')),
    path('admin/', admin.site.urls),
    # path('admin/', my_site.urls),
]

customer/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.deconstruct import deconstructible

import datetime

class Inquiry(models.Model):
    JOB_TYPES = (
        ('H', 'Hygiene'),
        ('T', 'Technical')
    )

    @property
    def gen_inq_number(self):
        time = datetime.datetime.now()
        self.inq_number = "INQ/{}/{}/{}/{}".format(time.year, time.month, time.day, self.id)
        inq = Inquiry.objects.get(id=self.id)
        inq.inq_number = self.inq_number
        inq.save()
        return self.inq_number


    # customer_name = models.ForeignKey(Customer, models.CASCADE)
    job_type = models.CharField(
        max_length=20,
        choices=JOB_TYPES,
        default="Hygiene"
    )
    recorded_by = models.ForeignKey(User, models.CASCADE)
    inspection_date = models.DateField(null=True)
    extra_details = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    inq_number = models.CharField(
        max_length=20,
        editable=False,
        null=True,
    )
    approve_job = models.BooleanField(default=False, null=True)



    def __str__(self):
        return "{}".format(self.gen_inq_number)


class Customer(models.Model):
    business_name = models.CharField(max_length=50, blank=True, null=True)
    location = models.CharField(max_length=100, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    phone_number = models.CharField(max_length=12)
    inquiry = models.OneToOneField(Inquiry, models.CASCADE, null=True, editable=True)

    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        """check for name that exists and return that name"""
        if self.business_name:
            return self.business_name
        else:
            return self.full_name

    def get_absolute_url(self):
        return reverse("customer:detail", kwargs={"pk": self.pk})

customer/forms.py
from django.forms import ModelForm
from .models import Customer, Inquiry

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['business_name', 'location', 'first_name', 'last_name','phone_number', 'inquiry']

class InquiryForm(ModelForm):
    class Meta:
        model = Inquiry
        fields = ['job_type', 'recorded_by', 'inspection_date', 'extra_details', 'approve_job']

customer/views.py
from django.views import generic
from backends.backend import Backend
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from .models import Customer, Inquiry
from .forms import InquiryForm, CustomerForm


class CustomerListView(generic.ListView):
    model = Customer
    context_template_name = "customer/customer_list.html"
    context_object_name = 'customers'

class CustomerDetailView(generic.DetailView):
    model = Customer

class CustomerUpdateView(generic.UpdateView):
    model = Customer
    fields = [
        'business_name', 'location',
        'first_name', 'last_name','phone_number'
    ]

class CustomerCreateView(generic.CreateView):
    model = Customer
    fields = [
        'business_name', 'location',
        'first_name', 'last_name','phone_number'
    ]

class CustomerDeleteView(generic.DeleteView):
    model = Customer
    context_template_name = "customer/customer_confirm_delete.html"
    context_object_name = 'customer'

    def get_success_url(self):
        return reverse('customer:index')

dag_backend/customer/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics, mixins
from customer.models import Customer, Inquiry
from customer.serializer import CustomerSerializer, InquirySerializer

# Create your views here.
class CustomerList(
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    generics.GenericAPIView):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     return self.create(request, *args, *kwargs)

class CustomerDetail(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    generics.GenericAPIView
    ):

    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

class InquiryList(
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    generics.GenericAPIView
    ):
    queryset = Inquiry.objects.all()
    serializer_class = InquirySerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

class InquiryDetail(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    generics.GenericAPIView):

    queryset = Inquiry.objects.all()
    serializer_class = InquirySerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

customer/templates/customer/customer_add.html
{% extends "layout.html" %}
{% block title %}
{{ title }}
{% endblock title %}
{% load widget_tweaks %}

{% block content %}
    <h3>{{ title }}</h3>
    <form action="#" method="POST">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div>
                    {{ field.label}}
                </div>
                <div>
                    {{ field|add_class:"form-control"}}
                </div>
            </div>
        {% endfor %}
        <div class="col">
            <button class="btn btn-primary mr-5" name="save">Save</button>
            <button class="btn btn-danger" name="delete">Delete</button>
        </div>
    </form>
{% endblock content %}

customer/templates/customer/customer_confirm_delete.html
{% extends "layout.html" %}
{% block title %}
Confim Delete
{% endblock title %}
{% block content %}
<h2>{{ customer }}</h2>
<hr/>
<p class="danger">Delete {{ customer }}?</p>
    <div class="form-group">
        <button class="btn bg-danger">Yes</button>
    </div>


{% endblock content %}

customer/templates/customer/customer_detail.html
{% extends "layout.html" %}
{% block title %}
{{ customer }}
{% endblock title %}
{% load widget_tweaks %}

{% block content %}
    <h3>{{ customer }}</h3>
    <hr/>
    <label><b>Name:</b></label> {{ customer.full_name }}<br/>
    <label><b>Location:</b></label> {{ customer.full_name }}<br/>
    <label><b>Phone Number:</b></label> {{ customer.full_name }}<br/>
    <label><b>Inquiry:</b></label> {{ customer.full_name }}<br/>

{% endblock content %}

customer/templates/customer/customer_form.html
{% extends "layout.html" %}
{% block title %}
Create Customer Inquiry
{% endblock title %}
{% load widget_tweaks %}

{% block content %}
    <h3>Create Customer Inquiry</h3>
    <hr/>
    <form action="#" method="POST">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div>
                    {{ field.label}}
                </div>
                <div>
                    {{ field|add_class:"form-control"}}
                </div>
            </div>
        {% endfor %}
        <div class="col">
            <button class="btn btn-primary mr-5" name="save">Save</button>
            <button class="btn btn-danger" name="delete">Delete</button>
        </div>
    </form>
{% endblock content %}

customer/templates/customer/customer_list.html
{% extends "layout.html" %}
{% block title %}
Customer List
{% endblock title %}

{% block content %}

    <table class="table">
        <thead>
            <tr>
            <th scope="col">INQ</th>
            <th scope="col">Business</th>
            <th scope="col">Contact Person</th>
            <th scope="col">Location</th>
            </tr>
        </thead>
        {% if customers %}
            {% for customer in customers %}
                <tbody>
                    <tr>
                        <td scope="row">{{ customer.inquiry.inq_number }}</td>
                        <td>
                            {% if customer.business_name %}
                                {{ customer.business_name }}
                            {% else %}
                                Personal Arrangement
                            {% endif %}
                        </td>
                        <td>{{ customer.full_name }}</td>
                        <td>{{ customer.location }}</td>
                        <td>
                            <a class="alert-primary" href="{% url 'customer:edit' pk=customer.pk %}">
                                <i class="fas fa-edit"></i>
                            </a>
                        </td>
                        <td>
                            <a class="alert-danger" href="{% url 'customer:delete' pk=customer.pk %}">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                 </tbody>
            {% endfor %}
        {% endif %}
    </table>
    <div class="col">
        <a href="{% url 'customer:add' %}"">
            <button id="addCustomerBtn" class="btn btn-primary mr-5">Add Customer</button>
        </a>
    </div>
{% endblock content %}

customer/templates/customer/inquiry_detail.html
{% extends "layout.html" %}
{% block title %}
{{ title }}
{% endblock title %}
{% load widget_tweaks %}

{% block content %}
    <h3>{{ inquiry.inq_number }}</h3>
    <form action="#" method="POST">
        {% for field in form %}
            <div class="form-group">
                <div>
                    {{ field.label}}
                </div>
                <div>
                    {{ field|add_class:"form-control"}}
                </div>
            </div>
        {% endfor %}
        <div class="col">
            <button class="btn btn-primary mr-5">Submit</button>
            <button class="btn btn-danger">Delete</button>
        </div>
    </form>
{% endblock content %}