customer/urls.py
from django.urls import path, reverse
from . import views

urlpatterns = [
    path('', views.CustomerListView.as_view(), name='index'),
    path('<int:pk>/', views.CustomerDetailView.as_view(), name="detail"),
    path('edit/<int:pk>/', views.CustomerUpdateView.as_view(), name='edit'),
    path('add/', views.CustomerCreateView.as_view(), name='add'),
    path('delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='delete'),
]

dag_backend/dag_backend/urls.py
from django.contrib import admin
from django.urls import path, include
# from customer.admin import my_site

urlpatterns = [
    path('customer/',include('customer.urls')),
     path('inspection/', include('inspection.urls')),
    path('admin/', admin.site.urls),
    # path('admin/', my_site.urls),
]

dag_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# from customer.admin import my_site

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('customer/',include(('customer.urls','customer'), namespace='customer')),
    path('inspection/', include(('inspection.urls','inspection'), namespace='inspection')),
    path('admin/', admin.site.urls),
    # path('admin/', my_site.urls),
]

inspection/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PropertyDetailList.as_view(), name='index'),
    path('detail/<int:pk>', views.PropertyDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.PropertyUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', views.PropertyDeleteView.as_view(), name='delete'),
    path('create/', views.PropertyCreateView.as_view(), name='create'),
]

inspection/models.py
from django.db import models
from customer.models import Customer
from django.contrib.auth.models import User


class Surface(models.Model):
    SURFACES = (
        ('1', 'Ceramic'),
        ('2', 'Porcelain'),
        ('3', 'Granite'),
        ('4', 'Grass'),
        ('5', 'Marble'),
        ('6', 'Terazzo'),
        ('7', 'Wood'),
        ('8', 'Trees'),
        ('9','Carpet'),
        ('10', 'PVC/ Vinly'),
        ('11', 'Rubber'),
        ('12', 'Flower Bed'),
        ('13', 'Paint'),
        ('14', 'Steel'),
        ('15', 'Cement'),
        ('16', 'Hedge'),
    )
    surfaces = models.CharField(max_length=12, null=True, choices=SURFACES)
    surface_area = models.IntegerField(null=True)
    others = models.CharField(max_length=12, null=True)

    def __str__(self):
        if self.surfaces:
            return "{0} {1} sqm".format(self.surfaces, self.surface_area)
        elif self.others:
            return "{0} {1} sqm".format(self.others, self.surface_area)
        else:
            return "N/A"

class Pest(models.Model):
    PESTS = (
        ('1', 'Mosquitoes'),
        ('2', 'Cockroaches'),
        ('3', 'Bats'),
        ('4', 'Rodents'),
        ('5', 'Bed bugs'),
        ('6', 'Termites'),
        ('7', 'Snakes'),
        ('8', 'Lizards'),
        ('9', 'Fleas'),
        ('10', 'Others')
    )
    pest_type = models.CharField(max_length=12, null=True, choices=PESTS)
    others_specify = models.CharField(max_length=12, null=True)

    def __str__(self):
        if self.pest_type:
            return "{}".format(self.pest_type)
        else:
            return "{}".format(self.others_specify)

class PropertyDetail(models.Model):
    PROP_TYPE = (
        ('PR', 'Public Residential'),
        ('PC', 'Public Commercial'),
        ('FP', 'Food Preparation'),
        ('WH', 'Warehouse/ Store'),
        ('PvR', 'Private Residential'),
        ('O', 'Others/ Specify')
    )

    SERVICES = (
        ('C', 'Cleaning'),
        ('G', 'Gardening'),
        ('PC', 'Pest Control')
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    recodered_by = models.ForeignKey(User, on_delete=models.CASCADE)
    property_type = models.CharField(
        max_length=12, choices=PROP_TYPE, default='Public Residential')
    services_required = models.CharField(
        max_length=12, choices=SERVICES, default='Cleaning')
    number_of_floors = models.IntegerField(null=True)
    estimated_area = models.IntegerField(null=True)
    number_of_occupants = models.IntegerField(null=True)
    description_of_terrain = models.TextField(null=True)
    surface = models.ForeignKey(Surface, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "{0} {1}".format(self.customer, self.property_type)

    def get_absolute_url(self):
        return reverse("inspection:detail", kwargs={"pk": self.pk})

inspection/views.py
from django.shortcuts import render, HttpResponse
from django.views import generic
from .models import PropertyDetail


class PropertyDetailList(generic.ListView):
    model = PropertyDetail
    context_template_name = "inpection/inspection_detail.html"
    context_object_name = "property_details"

class PropertyDetailView(generic.DetailView):
    model = PropertyDetail
    context_object_name = 'property_detail'

class PropertyUpdateView(generic.UpdateView):
    model = PropertyDetail
    fields = ['customer', 'recodered_by', 'property_type', 'services_required']
    context_object_name = 'property_detail'

class PropertyCreateView(generic.CreateView):
    model = PropertyDetail
    fields = ['customer', 'recodered_by', 'property_type', 'services_required']


class PropertyDeleteView(generic.DeleteView):
    model = PropertyDetail
    context_object_name = 'property_detail'

inspection/templates/inspection/propertydetail_confirm_delete.html
{% extends "layout.html" %}
{% block title %}
Confim Delete
{% endblock title %}
{% block content %}
<h2>{{ property_detail }}</h2>
<hr/>
<p class="danger">Delete {{ property_detail }}?</p>
    <div class="form-group">
        <button class="btn bg-danger">Yes</button>
    </div>


{% endblock content %}

inspection/templates/inspection/propertydetail_form.html
{% extends "layout.html" %}
{% block content %}
    {% for field in form %}
    <h3>{{ field.customer }}</h3>
        <div>
            <label>{{ field.label }}</label>: {{ field|title }}
        </div>
    {% endfor %}
{% endblock content %}

inspection/templates/inspection/propertydetail_list.html
{% extends "layout.html" %}
{% block title %}
Customer List
{% endblock title %}

{% block content %}

    <table class="table">
        <thead>
            <tr>
            <th scope="col">Customer</th>
            <th scope="col">Recorded By</th>
            <th scope="col">Property Type</th>
            <th scope="col">Service Required</th>
            </tr>
        </thead>
        {% if property_details %}
            {% for field in property_details %}
            {{ field }}
                <tbody>
                    <tr>
                        <td scope="row">{{ field.customer.full_name }}</td>
                        <td>{{ field.recorded_by }}</td>
                        <td>
                            <a class="alert-primary" href="{% url 'inspection:edit'  pk=field.pk %}">
                                <i class="fas fa-edit"></i>
                            </a>
                        </td>
                        <td>
                            <a class="alert-danger" href="{% url 'inspection:delete' pk=field.pk %}">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                 </tbody>
            {% endfor %}
        {% endif %}
    </table>
    <div class="col">
        <a href="{% url 'customer:add' %}"">
            <button id="addCustomerBtn" class="btn btn-primary mr-5">Add Customer</button>
        </a>
    </div>
{% endblock content %}