customer/urls.py
from django.urls import path, reverse
from . import views

urlpatterns = [
    path('', views.CustomerListView.as_view(), name='index'),
    path('<int:pk>/', views.CustomerDetailView.as_view(), name="detail"),
    path('edit/<int:pk>/', views.CustomerUpdateView.as_view(), name='edit'),
    path('add/', views.CustomerCreateView.as_view(), name='add'),
    path('delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='delete'),
]

dag_backend/dag_backend/urls.py
from django.contrib import admin
from django.urls import path, include
# from customer.admin import my_site

urlpatterns = [
    path('customer/',include('customer.urls')),
     path('inspection/', include('inspection.urls')),
    path('admin/', admin.site.urls),
    # path('admin/', my_site.urls),
]

dag_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# from customer.admin import my_site

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('customer/',include(('customer.urls','customer'), namespace='customer')),
    path('inspection/', include(('inspection.urls','inspection'), namespace='inspection')),
    path('admin/', admin.site.urls),
    # path('admin/', my_site.urls),
]

templates/index.html
{% extends "layout.html" %}
{% block title %}
{{ title }}
{% endblock title %}
{% block content %}
<div class="container">
    <h3>Welcome {{ user.username }} </h3>
    <div class="row">
    <div class="col-sm-4">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Hygiene Services</h5>
            <p class="card-text">summary of Cleaning Services we offer.</p>
            <a href="#" class="btn btn-primary">View Orders</a>
        </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Customers</h5>
            <p class="card-text">Different Customers we offer services to.</p>
            <a href="#" class="btn btn-primary">View Requests</a>
        </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Techical Services</h5>
            <p class="card-text">Range of technical Services offered</p>
            <a href="#" class="btn btn-primary">View Orders</a>
        </div>
        </div>
    </div>
    </div>
</div>

{% endblock content %}

templates/layout.html
<!doctype html>
{% load static from staticfiles %}
<html class="no-js" lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'styles/layout.css' %}"></link>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'home' %}">Dag and Bragan</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'customer:index' %}">Customers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inspection:index' %}">Inspections</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
        <div class="main-content">
        {% block content %}{% endblock content %}
        </div>
        <!--Footer section-->
        <footer class="footer">
          <p>Copyright of Dag & Bragan Uganda</p>
        </footer>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block title %} {{ title }}
{% endblock title %}
{% block content %}
    <div class="border border-primary rounded p-4 mx-auto">
        <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <div>
                        {{ field.label }}
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <button name="login" class="btn btn-primary">Login</button>
            </div>
            <div class="form-group">
                <label>Remember me </label> <input type="checkbox"/>
            </div>
        </form>
    </div>
    {% if message %}
        <div class="bg-alert">
            {{ message }}
        </div>
    {% endif %}



{% endblock content %}